export const videoGridConfig = {
    header: {
        title: "Discover Top Content",
    },
    categories: [
        "All",
        "Tech",
        "Gaming",
        "Entertainment",
        "Lifestyle",
        "Productivity",
    ],
    labels: {
        like: "Like",
    },
    videos: [
        {
            id: 1,
            category: "Tech",
            creator: "@sarahstyle",
            views: "120k",
            desc: "Summer OOTD #vibes",
            thumbnail: "bg-red-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 2,
            category: "Tech",
            creator: "@glamguru",
            views: "85k",
            desc: "My morning routine ✨",
            thumbnail: "bg-pink-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 3,
            category: "Gaming",
            creator: "@chef_mike",
            views: "2.1M",
            desc: "Best pasta recipe 🍝",
            thumbnail: "bg-orange-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 4,
            category: "Gaming",
            creator: "@fit_jane",
            views: "450k",
            desc: "Abs workout in 5 mins",
            thumbnail: "bg-green-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 5,
            category: "Entertainment",
            creator: "@menswear",
            views: "30k",
            desc: "Suit styling tips",
            thumbnail: "bg-blue-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 6,
            category: "Entertainment",
            creator: "@skincare",
            views: "1.2M",
            desc: "Glass skin secrets",
            thumbnail: "bg-purple-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 7,
            category: "Lifestyle",
            creator: "@tech_bro",
            views: "500k",
            desc: "New iPhone Unboxing",
            thumbnail: "bg-slate-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
        {
            id: 8,
            category: "Productivity",
            creator: "@baker_kate",
            views: "90k",
            desc: "Chocolate cake 🍫",
            thumbnail: "bg-yellow-100",
            type: "video",
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
        },
    ],
};
